import QtQuick 2.2
import MuseScore 3.0

MuseScore {
    menuPath: "Plugins.Fingering.Remove All Fingerings"
    version: "1.0"
    description: "Removes fingering placeholders, estimated fingering staff text, and native fingering elements."
    requiresScore: true

    // Safety: only removes text that looks like fingering generated by these plugins:
    // ?, single digits 0-4, or stacked/string labels such as A\n1, D\n3, G\n4, C\n0.
    property bool removeQuestionMarks: true
    property bool removeSingleDigitFingerings: true
    property bool removeStackedStringFingerings: true
    property bool removeNativeFingeringElements: true

    function normalizedText(element) {
        if (!element || element.text === undefined || element.text === null) return "";
        return String(element.text).replace(/^\s+|\s+$/g, "");
    }

    function isSingleDigitFingeringText(s) {
        return /^[0-4]$/.test(s);
    }

    function isStackedStringFingeringText(s) {
        return /^[ADGC]\s*\n\s*[0-4]$/.test(s);
    }

    function isInlineStringFingeringText(s) {
        return /^[ADGC][0-4]$/.test(s);
    }

    function isGeneratedFingeringStaffText(element) {
        if (!element || element.type != Element.STAFF_TEXT) return false;

        var s = normalizedText(element);

        if (removeQuestionMarks && s === "?") return true;
        if (removeSingleDigitFingerings && isSingleDigitFingeringText(s)) return true;
        if (removeStackedStringFingerings && isStackedStringFingeringText(s)) return true;
        if (removeStackedStringFingerings && isInlineStringFingeringText(s)) return true;

        return false;
    }

    function isNativeFingeringElement(element) {
        if (!removeNativeFingeringElements || !element) return false;

        // MuseScore exposes native fingering as Element.FINGERING in many plugin builds.
        // Guarded this way so the script still runs if that enum is unavailable.
        return Element.FINGERING !== undefined && element.type == Element.FINGERING;
    }

    function shouldRemove(element) {
        return isGeneratedFingeringStaffText(element) || isNativeFingeringElement(element);
    }

    function scanSegment(segment) {
        if (!segment || !segment.annotations) return;

        var annotations = segment.annotations;

        for (var i = annotations.length - 1; i >= 0; i--) {
            var element = annotations[i];

            if (shouldRemove(element)) {
                removeElement(element);
            }
        }
    }

    onRun: {
        if (!curScore) {
            Qt.quit();
            return;
        }

        var cursor = curScore.newCursor();

        curScore.startCmd();

        cursor.rewind(0); // score start

        while (cursor.segment) {
            scanSegment(cursor.segment);
            cursor.next();
        }

        curScore.endCmd();
        Qt.quit();
    }
}
